[package]
name = "hashing"
version = "0.1.0"
edition = "2021"

[dependencies]


[lib]
name = "hashing"

[dev-dependencies]
rand = "0.9.0"
criterion = "0.5"

[[bench]]
name = "bench"
harness = false

[profile.bench]
debug = true